project:
  type: website

website:
  title: "G1T1: Bangkok Greenery"
  navbar:
    left:
      - text: "Overview"
        href: overview.qmd
      - text: "Methodology"
        href: methodology.qmd
      - text: "Results & Discussion"
        href: resultsdiscussion.qmd  
      - text: "Project Proposal"
        href: projectproposal.qmd
      - text: "Lesson Learned"
        href: lessonlearned.qmd
      - text: "Poster"
        href: poster.qmd
      - text: "WebMap"
        href: webmap.qmd
    right:
      - text: "Home"
        href: index.qmd


format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



