project:
  type: website

website:
  title: "G1T1: project_name"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Project Proposal"
        href: projectproposal.qmd
      - text: "Methodology"
        href: methodology.qmd
      - text: "Results & Discussion"
        href: resultsdiscussion.qmd
      - text: "Lesson Learned"
        href: lessonlearned.qmd
      - text: "Poster"
        href: poster.qmd



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



